// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Token struct {
	ID             uuid.UUID
	AccessTokenKey uuid.UUID
	UserID         uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID        uuid.UUID
	Username  string
	CreatedAt time.Time
	UpdatedAt time.Time
	Password  string
}
