version: "3.9"


services:
  postgres:
    image: postgres
    container_name: CrudPostgres
    environment:
      POSTGRES_DB: "go-crud"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"