server:
  AppVersion: 1.0.0
  Port: :3000
  Mode: Development
  JwtSecretKey: secretToken
  TokenExpiresIn: 30m
  TokenRefreshExpiresIn: 48h
  BaseUrl: "http://localhost:3000"


postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: root
  PostgresqlPassword: root
  PostgresqlDBName: "go-crud"
  PostgresqlSSLMode: false

redis:
  RedisAddr: localhost:6379
  Password: "root"
  RedisDefaultDB: 16
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  RedisDB: 0
  DB: 0


